packaging_format = 2

id = "trustyhash"
name = "TrustyHash"
description.en = "SHA-256 Hash Calculator"
description.fr = "Calculateur de hachage SHA-256"

version = "1.0~ynh3"

maintainers = ["jarod5001"]

[upstream]
license = "MIT"
demo = "https://sprin.github.io/TrustyHash/"
userdoc = "https://github.com/sprin/TrustyHash"
code = "https://github.com/sprin/TrustyHash"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "300M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/trustyhash"

[resources]
        [resources.sources.main]
        url = "https://github.com/sprin/TrustyHash/archive/refs/heads/master.zip"
        sha256 = "52b48d4f6e18144424d158ad01e4adf0609a2d475792929b41265c56f5fa2d51"


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.2-fpm"
